export const sectionData = [
  {
    id: 1,
    className: 'section__1',
    src: 'bg-build1',
    header__title: 'Мы проектируем дома, которые реально построить',
    header__text:
      'Наш проект сэкономит вам деньги, будет соответствовать вашему бюджету и понятен любому строителю или дизайнеру',
    header__post_text_1:
      'Проект будет максимально соответствовать вашим пожеланиям',
    header__post_text_2:
      'Проект прогнозирует сроки и бережет ваш бюджет строительства',
    header__button: 'Записаться на расчет проекта',
    body__image:
      'https://thumb.tildacdn.com/tild3263-6662-4538-a165-653663363237/-/resize/714x/-/format/webp/Group_3.png',
    body__text: '',
  },
  {
    id: 2,
    className: 'section__2',
    src: 'bg-build2',
    header__title: 'О нас в цифрах',
    header__text: '',
    header__button: '',
    body__image: '',
    body__text:
      'Бесплатные консультации по проекту в течении срока строительства',
  },
  {
    id: 3,
    className: 'section__3',
    src: 'bg-build3',
    header__title: '',
    header__text: '',
    header__button: '',
    body__image: '',
    body__text: '',
  },
  {
    id: 4,
    className: 'section__4',
    src: 'bg-build4',
    header__title: '',
    header__text: '',
    header__button: '',
    body__image: '',
    body__text: '',
  },
  {
    id: 5,
    className: 'section__5',
    src: 'bg-build5',
    header__title: '',
    header__text: '',
    header__button: '',
    body__image: '',
    body__text: '',
  },
  {
    id: 6,
    className: 'section__6',
    src: 'bg-build6',
    header__title: '',
    header__text: '',
    header__button: '',
    body__image: '',
    body__text: '',
  },
  {
    id: 7,
    className: 'section__7',
    src: 'bg-build7',
    header__title: '',
    header__text: '',
    header__button: '',
    body__image: '',
    body__text: '',
  },
];
